apiVersion: v1
kind: ConfigMap
metadata:
  name: b-app-config
data:
  spring.config.name: application
  spring.config.location: file:///app/config/application.yaml
  application.yaml: |
    app:
      name: B
      version: v1
      service:
        suffix: -api-service
    spring:
      cloud:
        loadbalancer:
          ribbon:
            enable: false